### ISSUE TITLE
Endpoint for aggregations in metric tons

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1250]
also related:

We want to be able to get the information in 2 units of measurement: ODP Tonnes and MT. For example, in the old application (https://ozone-d7.edw.ro/countries/data) if you only select Methyl Bromide QPS Consumption from the first filter, you can then choose to display the information either in ODP Tonnes or in MT. You can either choose to allow a new parameter on GET to allow the user to change the unit of measurement or display the data in both unit of measurement.

**Comment by sorinstelian** [comment]
As part of the solution for this issue, will also add an endpoint for destructions in MT. The new endpoints will be:
```
/api/aggregations-mt/
/api/aggregations-destruction-mt/
```
Behavior will be similar to the corresponding existing `aggregations` and `aggregations-mt`, with one notable exception: `substance` will be use instead of `group` as a parameter for filtering and aggregation.
