### ISSUE TITLE
Data form - Submission info

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#291]
Right top text: "Respondents are requested to read the Introduction, the General Instructions, and the Definitions carefully before proceeding to the questionnaire and to refer to them as necessary when completing the data forms."

<img width="1697" alt="screenshot 2018-12-12 at 14 46 25" src="https://user-images.githubusercontent.com/533311/49870855-4f22fd80-fe1d-11e8-9c2a-cb92a16d8101.png">

Remove "Respondents are requested to read the Introduction in section 2, the General Instructions in section 4 and the Definitions in section 5 carefully before proceeding to the questionnaire and to refer to them as necessary when completing the data forms."

Remove form container border line.
Name, designation, organisation should have the same size, 50% of their current size.
Postal address is a text field.
Country must be drop-down list.
Phone, Fax, email and Date should have the same size, 30% of their current size.

Question: **Shouldn't we have a "Save and continue" button on each form?**

**Comment by mihai-macaneata** [comment]
> Question: Shouldn't we have a "Save and continue" button on each form?

The current "Save" button is a "Save and continue" button. 
Usually, users don't expect the application to close when pressing the save button. 

I think you're making this confusion because you are used to the django admin interface that has a weid ux pattern for the save button, but most other applications will just save stuff after pressing the save button

**Comment by melish** [comment]
> Question: Shouldn't we have a "Save and continue" button on each form?
My 2 cents: Simply "Save" is good enough
