### ISSUE TITLE
EPIC - Party/Secretariat account page.

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#533]
As a registered user in the System, I can change my account details:

- [ ]  Name
- [ ]  Email
- [ ]  Password
- [ ]  Language

I can see my role in the System and I can contact Secretariat to request a role upgrade (Party_RO -> Party).

Question: Should I see all my colleagues? (E.g. All reporters from Romania).

**Comment by alexkiro** [comment]
> * Password

FWIW, we already have a password change option (from Django), I don't think it's worth adding another one here.

**Comment by sorinstelian** [comment]
@nico4 @melish : taking into account the above comments, we are starting with implementing an endpoint for changing name, email and language.

**Comment by catalinjitea** [comment]
Backend part is done.

We can use `/current-user/<user_pk>` endpoint to update the account details of an user (first_name, last_name, email). For password we will use password change option from Django, like @alexkiro said.

Using the same endpoint, we can view the account of another user. That user should be a secretariat or from the same party. Using `/current-user` we will get account details of the logged in user.

Regarding to `Question: Should I see all my colleagues? (E.g. All reporters from Romania).`, if we decide that we want to see a list of "colleagues" I think we should make another issue.

**Comment by danmisailescu** [comment]
@catalinjitea  Why /current-user instead of returning a JSON with the current user information, returns an array with a single element, and in the code this destructuring hack is needed in order to extract the current user?  This hack assigns to state.currentUser the first element of the array returned from /current-user

setCurrentUser(state, data) {
	[state.currentUser] = data
}
I see we have /api/users/ for returning the list of users.

In the api description, under /api/current-user/ I see "Current User List" . Why? Is this intended to return an array of all the users under one party or managed by a secretariat? In this case what will the convention be? The first element of the array will be the secratariat user who called /current-user? 
![[Untitled].jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c0fcbafc51ee00011888144/125516c66e82c728ace21e0d46d3a194378b97a58aed8201e81fe086264c22703d46f9692586b32ee6447d070b0a47a8440d5f45ffad8e7ef0e23a25984019af80330b2b9b645bf9fa9015ad00b32a8a4a81beb58949c2ed3c22e18a9d02.jpg)

**Comment by danmisailescu** [comment]
@catalinjitea  I found a problem while testing the endpoint:
PUT http://localhost:8000/api/current-user/2/ 400 (Bad Request)
{"language":["Incorrect type. Expected pk value, received str."]}

The language should be a string representing the languageKey: 'ar', 'zh', 'en', etc... from 
availableLanguages: {
			ar: 'العربية',
			zh: '中文',
			en: 'English',
			fr: 'Français',
			ru: 'Русский',
			es: 'Español'
		},

**Comment by sorinstelian** [comment]
@danmisailescu : the structure of the responses for all endpoints was generally decided or at least agreed together with @mihai-macaneata.
You are right in your assessment that this endpoint should return a different format, but is it of real value to the project to change this now?

**Comment by catalinjitea** [comment]
@danmisailescu for the first question please check @sorinstelian's reply.

For the second question, indeed we need to allow pass the iso code instead of id.
