### ISSUE TITLE
The flags  “Valid” and “Superseded” should not be visible in the data entry screens.

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#592]
The flags  “Valid” and “Superseded” should not be visible in the data entry screens.  These flags are never edited directly but are the result of certain actions in the workflow.

@melish, who should see them?

**Comment by sorinstelian** [comment]
My take is that the Valid/Superseded flags should be indeed only visible in the dashboard for every submission that supports them (Exemption submissions, for example, aren't superseded). These flags make no sense in the Data Entry state.

**Comment by sorinstelian** [comment]
Actually, to complete the above comment, the Valid flag should be settable, only by the Secretariat, only at the transition between Processing and Finalized.

**Comment by melish** [comment]
1. Flag "Valid" should only be visible for submissions in state "Finalized" (which are always read only), for both secretariat and parties.
@nico4 please add explanation about confirmation screen when changing state from "processing" to "finalized".

Since a checkbox will not be used to set the value of this field, we don't need to show it together with the rest of the flags. It would be better to show the "Invalid" value more prominently (e.g. as a label called "Valid" or "Invalid", close to the submission status - which should also be displayed somewhere in the UI).

2. Flag Superseded is not directly editable and should only be visible for superseded submissions.
The same principle applies - it's enough to show a label "Superseded" instead of the checkbox.

**Comment by sorinstelian** [comment]
I think there should also be a way of modifying this flag for Finalized submissions, in case the data turns out to actually be incorrect after finalizing.

**Comment by melish** [comment]
To be continued on #643
