### ISSUE TITLE
Exemption - Secretariat cannot save data in the Nomination/Approved forms

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#648]

**Comment by danmisailescu** [comment]
@sorinstelian  Could not reproduce. 

Secretariat can save data in both Exemption tabs Nomination and Approved. 
Maybe you saw validation errors because the Submission Info tab had missing information

After refresh I see the newly added data.
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c0fcbafc51ee00011888144/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f6282083ba2eb9447f04565b4bf941595c10fbacdf7fa0e32e6c981e5ab38532022d8c6853beb2901eb90bbb258e4e86bfba8b4cc6e83521f5c6.png)

**Comment by sorinstelian** [comment]
Indeed, it seems solved, probably as a side-effect of other changes. Closing.
