### ISSUE TITLE
View or Continue

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#676]
As Party, I created a submission for Article7 for 2018. As Secretariat, I created the same submission. 

I don't understand why the actions are different for Part and Secretariat. 

party: https://cl.ly/53df9a0d233e
secretariat: https://cl.ly/e920d0662cae

**Comment by nico4** [comment]
Nevermind, this works.

**Comment by nico4** [comment]
https://www.useloom.com/share/a5907d7e267e494192bdd2573a798519

**Comment by sorinstelian** [comment]
@nico4 @mihai-macaneata : The available actions listed in the "All Submissions" section are different than the ones in the "Data Entry" section. Was this specified like this?

Also, since we now allow both OS and Party users to have data entry submissions open at the same time, what should a user see in the "Data Entry" section? Only those created by his type of user (party/OS)? Both? I assume both, but it's never bad to ask. :)

**Comment by mihai-macaneata** [comment]
Can't reproduce

**Comment by melish** [comment]
probably fixed
