### ISSUE TITLE
Wrong site URL in password reset e-mail

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#839]
The reset password link from the email received is redirecting me to https://example.com website. 

https://cl.ly/d733cb437dc6

**Comment by melish** [comment]
This is because the URL is taken from the "Sites" model:

https://ozone-staging.edw.ro/admin/sites/site/1/change/

After manually changing, it works. However, it's reset on every drop/recreate of the database.

![image](https://user-images.githubusercontent.com/1218168/56296754-c9e78680-6137-11e9-9ed2-fbdbbec09eb1.png)

**Comment by melish** [comment]
I don't think we need to set the site name automatically, as long as we don't forget to set it when dropping the database.
